network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
#    ens4:
#      dhcp4: false
#      addresses: [ 192.168.0.10/24 ]
#      gateway4: 192.168.0.1
#      nameservers:
#        addresses: [8.8.8.8]
